[package]
name = "humility-cmd-probe"
version = "0.1.0"
edition = "2021"
description = "probe for any attached devices"

[dependencies]
humility = { path = "../../humility-core", package = "humility-core" }
humility-cortex = { path = "../../humility-arch-cortex" }
humility-cmd = { path = "../../humility-cmd" }
structopt = "0.3"
anyhow = { version = "1.0.44", features = ["backtrace"] }
log = {version = "0.4.8", features = ["std"]}
num-traits = "0.2"
