[package]
name = "humility-cmd-readmem"
version = "0.1.0"
edition = "2021"
description = "read and display memory region"

[dependencies]
humility = { path = "../../humility-core", package = "humility-core" }
humility-cmd = { path = "../../humility-cmd" }
structopt = "0.3"
anyhow = { version = "1.0.44", features = ["backtrace"] }
parse_int = "0.4.0"
